loadBackground("data/scenario/remilia/effect/ED000.png")
loadBackground(packPath.."/ED001.png")
loadBackground(packPath.."/ED002.png")

addCommand('playBGM "data/bgm/ta06.ogg"')
addCommand("text Autumn at the Scarlet Devil Manor.")
addCommand("text This devil's manor, surrounded by roses,")
addCommand("text A place that should be peaceful again.")
addCommand("text This was the hope of the maid.")
addCommand('clear')
addCommand("text After a long day of work,")
addCommand("text and a task well accomplished,")
addCommand("text it was time to come home...")
addCommand("text Or so she thought")
addCommand('clear')
addCommand("text But as she would learn soon,")
addCommand("text her struggles were to no avail.")
addCommand("background 1")
addCommand('text Remi   "Welcome back Sakuya,')
addCommand('text         Did you have fun outside?"')
addCommand('text Sakuya "It was very interesting,')
addCommand('text         but I wonder if the party has stopped?"')
addCommand('clear')
addCommand('text Patchy "No, not at all, in fact,')
addCommand('text         there are more guests coming as we are speaking."')
addCommand('text Sakuya "I see, It seems like I was misled."')
addCommand('clear')
addCommand('text Patchy "Did you think that everything was over?"')
addCommand('text Remi   "Of course it\'s not over, the party is only starting after all."')
addCommand('text Sakuya "Well it isn\'t that bad to have guests once in a while, I imagine."')
addCommand('text Patchy "That is a strange reaction coming from you Sakuya..."')

addCommand("background 2")
addCommand('text Remi   "It seems like you understood something.')
addCommand('text         And as a maid shouldn\'t you be glad to see your work appreciated by others?"')
addCommand('text Sakuya "I would if they weren\'t causing so much trouble...')
addCommand('text         But maybe the yama would be glad if I let everyone in all the time."')
addCommand('clear')
addCommand('text Patchy "There wouldn\'t be many books left if you were to do that."')
addCommand('text Sakuya "I\'m still curious about the mistress\' findings. Did you help her, lady Patchouli?"')
addCommand('text Remi   "No she didn\'t, but you\'ll find someone quite helpful nearby..')
addCommand('text         But be quick, we are waiting for the tea."')
addCommand('clear')
addCommand('text Patchy "Should I go too? I\'m rather curious."')
addCommand('text Remi   "No, there is something I would like to tell you."')
addCommand('text Patchy "You need me for one of your little plays, aren\'t you?"')

addCommand('playBGM ""')
addCommand("end")
addCommand('text And after that, Sakuya wandered,')
addCommand('text knowing the Mistress was having fun,')
addCommand('text thinking of who Remilia mentioned.')
addCommand('text Now the chase had finally begun.')

addCommand('clear')
addCommand('text As for Remilia and Patchouli,')
addCommand('generateGameAnimation '..packPath..'staffroll.txt')
addCommand('playGameAnimation '..packPath..'staffroll_generated.txt')
addCommand('playBGM "data/bgm/sr.ogg"')
addCommand('text they were simply talking and thinking')
addCommand('text on how to make this simple party')
addCommand('text slightly more fun, and quite confusing.')



--addCommand('playAnimation '..packPath..'outroAnimation.lua')

--addCommand('playBGM "data/bgm/st00.ogg"')
--addCommand("text This is outro two")
--addCommand("color FF0000 FFFFFF")
--addCommand("text This is outro two [colored]")
--addCommand("clear")
--addCommand("text This is outro two [colored again]")
--addCommand("color FF00FF FFFFFF")
--addCommand("text This is outro two [colorised]")
--addCommand("color FFFFFF FFFFFF")
--addCommand("text This is outro two [colorised no more]")
--addCommand("background 1")
--addCommand("clear")
--addCommand("text New background !!!??? :scream:")
--addCommand("end")
--addCommand("text This is the new feature everyone wanted.")
--addCommand("text It is now a thing.")
--addCommand("text I hope everyone will like it.")
--addCommand("clear")
--addCommand("text Ending A.")