local names = {
	reimu = "Reimu Hakurei",
	marisa = "Marisa Kirisame",
	sakuya = "Sakuya Izayoi",
	alice = "Alice Margatroid",
	patchouli = "Patchouli Knowledge",
	youmu = "Youmu Konpaku",
	remilia = "Remilia Scarlet",
	yuyuko = "Yuyuko Saigyouji",
	yukari = "Yukari Yakumo",
	suika = "Suika Ibuki",
	udonge = "Reisen Udongein Inaba",
	aya = "Aya Shameimaru",
	komachi = "Komachi Onozuka",
	iku = "Iku Nagae",
	tenshi = "Tenshi Hinanawi",
	sanae = "Sanae Kochiya",
	chirno = "Cirno",
	meirin = "Hong Meiling",
	utsuho = "Utsuho Reiuji",
	suwako = "Suwako Moriya",
}
local animations = {
	alice = {
		walk = {
			{
				image = 'data/character/alice/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/walkFront009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 128,
				xoffset = 54,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/alice/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand010.cv0',
				index = 10,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand011.cv0',
				index = 11,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand012.cv0',
				index = 12,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand013.cv0',
				index = 13,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand014.cv0',
				index = 14,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/alice/stand015.cv0',
				index = 15,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 128,
				xoffset = 51,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	aya = {
		walk = {
			{
				image = 'data/character/aya/walkFront007.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 49,
				texheight = 100,
				xoffset = 62,
				yoffset = 199,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront000.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 47,
				texheight = 101,
				xoffset = 58,
				yoffset = 201,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront001.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 100,
				xoffset = 60,
				yoffset = 199,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront002.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 62,
				texheight = 100,
				xoffset = 64,
				yoffset = 197,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront003.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 51,
				texheight = 101,
				xoffset = 64,
				yoffset = 199,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront004.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 47,
				texheight = 102,
				xoffset = 56,
				yoffset = 201,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront005.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 56,
				texheight = 101,
				xoffset = 59,
				yoffset = 199,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/walkFront006.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 99,
				xoffset = 71,
				yoffset = 197,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/aya/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 50,
				texheight = 100,
				xoffset = 62,
				yoffset = 198,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 51,
				texheight = 99,
				xoffset = 64,
				yoffset = 196,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 99,
				xoffset = 64,
				yoffset = 196,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 100,
				xoffset = 64,
				yoffset = 198,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 103,
				xoffset = 64,
				yoffset = 204,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 102,
				xoffset = 64,
				yoffset = 202,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 102,
				xoffset = 60,
				yoffset = 202,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/aya/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 102,
				xoffset = 64,
				yoffset = 202,
				duration = 5,
				rendergroup = 0,
			},
		},
	},
	chirno = {
		walk = {
			{
				image = 'data/character/chirno/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 76,
				xoffset = 62,
				yoffset = 188,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 76,
				xoffset = 62,
				yoffset = 190,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 76,
				xoffset = 62,
				yoffset = 191,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 76,
				xoffset = 62,
				yoffset = 190,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 76,
				xoffset = 62,
				yoffset = 188,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 75,
				xoffset = 62,
				yoffset = 184,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 74,
				xoffset = 62,
				yoffset = 181,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 75,
				xoffset = 62,
				yoffset = 184,
				duration = 4,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/chirno/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 78,
				xoffset = 74,
				yoffset = 190,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 77,
				xoffset = 68,
				yoffset = 192,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 77,
				xoffset = 74,
				yoffset = 194,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 77,
				xoffset = 68,
				yoffset = 195,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 77,
				xoffset = 74,
				yoffset = 194,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/chirno/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 78,
				xoffset = 68,
				yoffset = 194,
				duration = 5,
				rendergroup = 0,
			},
		},
	},
	iku = {
		walk = {
			{
				image = 'data/character/iku/walkFrontB000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 120,
				xoffset = 51,
				yoffset = 247,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/walkFrontB001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 118,
				xoffset = 51,
				yoffset = 243,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/walkFrontB002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 125,
				xoffset = 47,
				yoffset = 257,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/walkFrontB003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 123,
				xoffset = 49,
				yoffset = 253,
				duration = 4,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/iku/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 60,
				texheight = 121,
				xoffset = 58,
				yoffset = 247,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 58,
				texheight = 122,
				xoffset = 58,
				yoffset = 248,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 118,
				xoffset = 54,
				yoffset = 239,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 117,
				xoffset = 54,
				yoffset = 236,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 56,
				texheight = 118,
				xoffset = 54,
				yoffset = 238,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 119,
				xoffset = 54,
				yoffset = 241,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 58,
				texheight = 120,
				xoffset = 56,
				yoffset = 244,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 120,
				xoffset = 60,
				yoffset = 245,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/iku/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 62,
				texheight = 120,
				xoffset = 60,
				yoffset = 245,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	komachi = {
		walk = {
			{
				image = 'data/character/komachi/walkFront003.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 102,
				xoffset = 88,
				yoffset = 201,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront004.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 79,
				texheight = 104,
				xoffset = 88,
				yoffset = 205,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront005.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 104,
				xoffset = 90,
				yoffset = 205,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront006.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 104,
				xoffset = 90,
				yoffset = 205,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront007.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 81,
				texheight = 103,
				xoffset = 92,
				yoffset = 203,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront008.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 81,
				texheight = 103,
				xoffset = 92,
				yoffset = 203,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront009.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 79,
				texheight = 101,
				xoffset = 90,
				yoffset = 199,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront010.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 101,
				xoffset = 88,
				yoffset = 199,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront011.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 102,
				xoffset = 88,
				yoffset = 201,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront012.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 79,
				texheight = 104,
				xoffset = 88,
				yoffset = 205,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront013.cv0',
				index = 10,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 104,
				xoffset = 90,
				yoffset = 205,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront014.cv0',
				index = 11,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 104,
				xoffset = 90,
				yoffset = 205,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront015.cv0',
				index = 12,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 81,
				texheight = 103,
				xoffset = 92,
				yoffset = 203,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront000.cv0',
				index = 13,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 81,
				texheight = 103,
				xoffset = 92,
				yoffset = 203,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront001.cv0',
				index = 14,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 79,
				texheight = 101,
				xoffset = 90,
				yoffset = 199,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/walkFront002.cv0',
				index = 15,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 101,
				xoffset = 88,
				yoffset = 199,
				duration = 4,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/komachi/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 91,
				texheight = 106,
				xoffset = 109,
				yoffset = 209,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 89,
				texheight = 106,
				xoffset = 107,
				yoffset = 209,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 88,
				texheight = 107,
				xoffset = 109,
				yoffset = 211,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 88,
				texheight = 108,
				xoffset = 109,
				yoffset = 213,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 89,
				texheight = 107,
				xoffset = 109,
				yoffset = 211,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 90,
				texheight = 106,
				xoffset = 105,
				yoffset = 209,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 91,
				texheight = 105,
				xoffset = 105,
				yoffset = 207,
				duration = 8,
				rendergroup = 0,
			},
			{
				image = 'data/character/komachi/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 92,
				texheight = 105,
				xoffset = 107,
				yoffset = 207,
				duration = 8,
				rendergroup = 0,
			},
		},
	},
	marisa = {
		walk = {
			{
				image = 'data/character/marisa/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 218,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 216,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 216,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 218,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 218,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 218,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 218,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 71,
				yoffset = 218,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/marisa/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/marisa/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 109,
				xoffset = 63,
				yoffset = 214,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	meirin = {
		walk = {
			{
				image = 'data/character/meirin/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 94,
				xoffset = 46,
				yoffset = 185,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 95,
				xoffset = 48,
				yoffset = 187,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 49,
				texheight = 95,
				xoffset = 50,
				yoffset = 187,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 50,
				texheight = 94,
				xoffset = 48,
				yoffset = 185,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 93,
				xoffset = 50,
				yoffset = 183,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 51,
				texheight = 93,
				xoffset = 50,
				yoffset = 183,
				duration = 5,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/meirin/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 92,
				xoffset = 58,
				yoffset = 181,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 93,
				xoffset = 58,
				yoffset = 183,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 94,
				xoffset = 58,
				yoffset = 185,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 95,
				xoffset = 58,
				yoffset = 187,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 93,
				xoffset = 58,
				yoffset = 183,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/meirin/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 92,
				xoffset = 58,
				yoffset = 181,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	patchouli = {
		walk = {
			{
				image = 'data/character/patchouli/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/walkFront009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 48,
				texheight = 102,
				xoffset = 48,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/patchouli/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 212,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 212,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 211,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 213,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 215,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 217,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 216,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 216,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 217,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 215,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand010.cv0',
				index = 10,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 213,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/patchouli/stand011.cv0',
				index = 11,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 105,
				xoffset = 57,
				yoffset = 211,
				duration = 5,
				rendergroup = 0,
			},
		},
	},
	reimu = {
		walk = {
			{
				image = 'data/character/reimu/walkFront000 .cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront001 .cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 241,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront002 .cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront003 .cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront004 .cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront005 .cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront006 .cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/walkFront007 .cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 69,
				yoffset = 242,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/reimu/stand002 .cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand003 .cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand004 .cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand005 .cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand006 .cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand007 .cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand008 .cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand009 .cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand000 .cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/reimu/stand001 .cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 90,
				yoffset = 234,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	remilia = {
		walk = {
			{
				image = 'data/character/remilia/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 148,
				yoffset = 252,
				duration = 4,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/remilia/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/remilia/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 128,
				xoffset = 145,
				yoffset = 251,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	sakuya = {
		walk = {
			{
				image = 'data/character/sakuya/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/walkFront008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 74,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/sakuya/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/sakuya/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 254,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	sanae = {
		walk = {
			{
				image = 'data/character/sanae/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 93,
				xoffset = 46,
				yoffset = 184,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 94,
				xoffset = 50,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 94,
				xoffset = 56,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 93,
				xoffset = 56,
				yoffset = 184,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 62,
				texheight = 93,
				xoffset = 58,
				yoffset = 184,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 94,
				xoffset = 58,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 58,
				texheight = 95,
				xoffset = 54,
				yoffset = 188,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 94,
				xoffset = 52,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/sanae/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 69,
				texheight = 95,
				xoffset = 64,
				yoffset = 188,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 96,
				xoffset = 62,
				yoffset = 190,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 76,
				texheight = 96,
				xoffset = 60,
				yoffset = 190,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 81,
				texheight = 96,
				xoffset = 60,
				yoffset = 190,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 84,
				texheight = 95,
				xoffset = 56,
				yoffset = 188,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 78,
				texheight = 94,
				xoffset = 60,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 62,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/sanae/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 64,
				yoffset = 186,
				duration = 7,
				rendergroup = 0,
			},
		},
	},
	suika = {
		walk = {
			{
				image = 'data/character/suika/walkFront001.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront002.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront003.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront004.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront005.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront006.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront007.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/walkFront000.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 94,
				xoffset = 47,
				yoffset = 187,
				duration = 3,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/suika/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand010.cv0',
				index = 10,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand011.cv0',
				index = 11,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand012.cv0',
				index = 12,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand013.cv0',
				index = 13,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand014.cv0',
				index = 14,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand015.cv0',
				index = 15,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand016.cv0',
				index = 16,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/suika/stand017.cv0',
				index = 17,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 128,
				texheight = 109,
				xoffset = 145,
				yoffset = 211,
				duration = 7,
				rendergroup = 0,
			},
		},
	},
	suwako = {
		walk = {
			{
				image = 'data/character/suwako/walkFront009.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 71,
				xoffset = 58,
				yoffset = 140,
				duration = 2,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/walkFront004.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 85,
				xoffset = 52,
				yoffset = 168,
				duration = 14,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/walkFront005.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 91,
				xoffset = 42,
				yoffset = 182,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/walkFront006.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 94,
				xoffset = 58,
				yoffset = 186,
				duration = 4,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/walkFront007.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 56,
				texheight = 90,
				xoffset = 62,
				yoffset = 182,
				duration = 3,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/suwako/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 49,
				texheight = 65,
				xoffset = 46,
				yoffset = 128,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 51,
				texheight = 65,
				xoffset = 46,
				yoffset = 128,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 51,
				texheight = 65,
				xoffset = 44,
				yoffset = 128,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 63,
				xoffset = 44,
				yoffset = 124,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 62,
				xoffset = 44,
				yoffset = 122,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 61,
				xoffset = 44,
				yoffset = 120,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 62,
				xoffset = 46,
				yoffset = 122,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/suwako/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 51,
				texheight = 63,
				xoffset = 48,
				yoffset = 124,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	tenshi = {
		walk = {
			{
				image = 'data/character/tenshi/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 58,
				texheight = 101,
				xoffset = 71,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 57,
				texheight = 101,
				xoffset = 71,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 101,
				xoffset = 79,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 61,
				texheight = 100,
				xoffset = 73,
				yoffset = 198,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 53,
				texheight = 100,
				xoffset = 61,
				yoffset = 198,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 52,
				texheight = 101,
				xoffset = 59,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 56,
				texheight = 101,
				xoffset = 63,
				yoffset = 200,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 100,
				xoffset = 61,
				yoffset = 198,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/tenshi/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 55,
				texheight = 103,
				xoffset = 55,
				yoffset = 202,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 54,
				texheight = 104,
				xoffset = 59,
				yoffset = 204,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 103,
				xoffset = 71,
				yoffset = 202,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 68,
				texheight = 103,
				xoffset = 71,
				yoffset = 202,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 67,
				texheight = 105,
				xoffset = 63,
				yoffset = 206,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 63,
				texheight = 104,
				xoffset = 57,
				yoffset = 204,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 59,
				texheight = 101,
				xoffset = 57,
				yoffset = 198,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/tenshi/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 58,
				texheight = 101,
				xoffset = 57,
				yoffset = 198,
				duration = 7,
				rendergroup = 0,
			},
		},
	},
	udonge = {
		walk = {
			{
				image = 'data/character/udonge/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 113,
				xoffset = 88,
				yoffset = 226,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 78,
				texheight = 112,
				xoffset = 88,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 79,
				texheight = 113,
				xoffset = 88,
				yoffset = 222,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 78,
				texheight = 114,
				xoffset = 88,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 115,
				xoffset = 88,
				yoffset = 226,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 79,
				texheight = 114,
				xoffset = 90,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 82,
				texheight = 113,
				xoffset = 94,
				yoffset = 222,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 81,
				texheight = 112,
				xoffset = 94,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/udonge/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 72,
				texheight = 114,
				xoffset = 81,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 114,
				xoffset = 73,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 60,
				texheight = 114,
				xoffset = 63,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 56,
				texheight = 114,
				xoffset = 53,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 62,
				texheight = 115,
				xoffset = 61,
				yoffset = 226,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 68,
				texheight = 114,
				xoffset = 71,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 71,
				texheight = 115,
				xoffset = 77,
				yoffset = 226,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 75,
				texheight = 115,
				xoffset = 85,
				yoffset = 226,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/udonge/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 77,
				texheight = 114,
				xoffset = 89,
				yoffset = 224,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	utsuho = {
		walk = {
			{
				image = 'data/character/utsuho/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 114,
				xoffset = 122,
				yoffset = 228,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 113,
				xoffset = 142,
				yoffset = 226,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 122,
				texheight = 113,
				xoffset = 150,
				yoffset = 226,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 113,
				xoffset = 144,
				yoffset = 226,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 114,
				texheight = 113,
				xoffset = 134,
				yoffset = 226,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 113,
				xoffset = 126,
				yoffset = 226,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 106,
				texheight = 114,
				xoffset = 118,
				yoffset = 228,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 114,
				xoffset = 116,
				yoffset = 228,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/utsuho/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 108,
				xoffset = 142,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 108,
				xoffset = 136,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 108,
				xoffset = 132,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 108,
				xoffset = 132,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 104,
				texheight = 108,
				xoffset = 132,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 108,
				xoffset = 138,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 108,
				xoffset = 142,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 108,
				xoffset = 136,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 108,
				xoffset = 132,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 108,
				xoffset = 132,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand010.cv0',
				index = 10,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 104,
				texheight = 108,
				xoffset = 132,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand011.cv0',
				index = 11,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 109,
				xoffset = 138,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand012.cv0',
				index = 12,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 109,
				xoffset = 142,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand013.cv0',
				index = 13,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 109,
				xoffset = 136,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand014.cv0',
				index = 14,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 109,
				xoffset = 132,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand015.cv0',
				index = 15,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 109,
				xoffset = 132,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand016.cv0',
				index = 16,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 104,
				texheight = 109,
				xoffset = 132,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand017.cv0',
				index = 17,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 109,
				xoffset = 138,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand018.cv0',
				index = 18,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 109,
				xoffset = 142,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand019.cv0',
				index = 19,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 109,
				xoffset = 136,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand020.cv0',
				index = 20,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 109,
				xoffset = 132,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand021.cv0',
				index = 21,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 105,
				texheight = 109,
				xoffset = 132,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand022.cv0',
				index = 22,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 104,
				texheight = 109,
				xoffset = 132,
				yoffset = 220,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/utsuho/stand023.cv0',
				index = 23,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 108,
				texheight = 108,
				xoffset = 138,
				yoffset = 218,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	youmu = {
		walk = {
			{
				image = 'data/character/youmu/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/walkFront009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 110,
				texheight = 90,
				xoffset = 148,
				yoffset = 175,
				duration = 6,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/youmu/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/youmu/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 118,
				texheight = 88,
				xoffset = 138,
				yoffset = 171,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
	yukari = {
		walk = {
			{
				image = 'data/character/yukari/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/walkFront007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 80,
				texheight = 124,
				xoffset = 71,
				yoffset = 247,
				duration = 7,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/yukari/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
			{
				image = 'data/character/yukari/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 119,
				texheight = 116,
				xoffset = 142,
				yoffset = 227,
				duration = 5,
				rendergroup = 0,
			},
		},
	},
	yuyuko = {
		walk = {
			{
				image = 'data/character/yuyuko/walkFront000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 230,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/walkFront001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 230,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/walkFront002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 230,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/walkFront003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 230,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/walkFront004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 230,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/walkFront005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 64,
				yoffset = 230,
				duration = 6,
				rendergroup = 0,
			},
		},
		stand = {
			{
				image = 'data/character/yuyuko/stand000.cv0',
				index = 0,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 239,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand001.cv0',
				index = 1,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 239,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand002.cv0',
				index = 2,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 239,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand003.cv0',
				index = 3,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 239,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand004.cv0',
				index = 4,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 240,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand005.cv0',
				index = 5,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 241,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand006.cv0',
				index = 6,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 241,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand007.cv0',
				index = 7,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 241,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand008.cv0',
				index = 8,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 241,
				duration = 6,
				rendergroup = 0,
			},
			{
				image = 'data/character/yuyuko/stand009.cv0',
				index = 9,
				unknown = 0,
				xtexoffset = 0,
				ytexoffset = 0,
				texwidth = 64,
				texheight = 128,
				xoffset = 63,
				yoffset = 240,
				duration = 6,
				rendergroup = 0,
			},
		},
	},
}

return {
	names = names,
	animations = animations
}