//
// Created by PinkySmile on 04/11/2020.
//

#ifndef HISOUTENSOKUDISCORDINTEGRATION_GETPUBLICIP_HPP
#define HISOUTENSOKUDISCORDINTEGRATION_GETPUBLICIP_HPP

extern char *myIp;

const char *getMyIp();

#endif // HISOUTENSOKUDISCORDINTEGRATION_GETPUBLICIP_HPP
